# Nome da Aplicação
spring.application.name=pratica3SD

# Configuração do Servidor Web (Tomcat)
server.port=8080
spring.main.web-application-type=servlet

# Conexão com o PostgreSQL do Docker
spring.datasource.url=jdbc:postgresql://localhost:5434/testdb
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 'update' cria automaticamente as tabelas e colunas com base nas suas entidades Java
spring.jpa.hibernate.ddl-auto=update
# Mostra no console do IntelliJ os comandos SQL que o Spring executar
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Desativa o aviso chato de Open-In-View no console
spring.jpa.open-in-view=false

# Caminho personalizado para acessar a interface visual do Swagger
springdoc.swagger-ui.path=/swagger-ui.html

# Caminho para exportar a documentação no formato JSON (caso precise importar no Postman/Insomnia)
springdoc.api-docs.path=/api-docs

# ==========================================
# NOVAS CONFIGURAÇÕES: MENSAGERIA E IOT
# ==========================================

# 1. Configurações do RabbitMQ (Onde o backend vai ESCUTAR os sensores)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=12345

# 2. Configurações do Mosquitto / MQTT (Onde o backend vai PUBLICAR para o Frontend)
mqtt.broker.url=tcp://192.168.0.9:1883
mqtt.client.id=backend-publisher-spring
mqtt.topic.dashboard=dashboard/telemetria
mqtt.topic.alertas=dashboard/alertas